version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=super-secret-humanity-key-2026
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
